version: "3"

networks:
  ci4:


services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - ./src:/code
    networks:
      - ci4

  db:
    image: mariadb
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql:/var/lib/mysql
    networks:
      - ci4
    environment:
      MYSQL_ROOT_PASSWORD: rahasia

  nginx:
    image: nginx:1.19.0-alpine
    restart: always
    ports:
      - "8888:80"
    volumes:
      - ./src:/code
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - ci4
